// <auto-generated />
namespace ODHDEVELOPERS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class lauda : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lauda));
        
        string IMigrationMetadata.Id
        {
            get { return "202103090555023_lauda"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
