// <auto-generated />
namespace ODHDEVELOPERS.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class migra : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migra));
        
        string IMigrationMetadata.Id
        {
            get { return "202103110902170_migra"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
