// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 7.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_blinds(l,k,a){var g=jQuery;var j=g(this);var c=l.parts||3;var h=g("<div>").addClass("ws_effect ws_blinds").css({position:"absolute",width:"100%",height:"100%",left:0,top:0,"z-index":8}).hide().appendTo(a);var d=g("<div>").css({position:"absolute",top:0,left:0,width:"100%",height:"100%",overflow:"hidden"}).appendTo(h);var e=[];var b=document.addEventListener;for(var f=0;f<c;f++){e[f]=g("<div>").css({position:b?"relative":"absolute",display:b?"inline-block":"block",height:"100%",width:(100/c+0.001).toFixed(3)+"%",border:"none",margin:0,overflow:"hidden",top:0,left:b?0:((100*f/c).toFixed(3)+"%")}).appendTo(h)}this.go=function(q,o,n){if(n==undefined){n=o>q?1:0}h.find("img").stop(true,true);h.show();var t=g(".ws_list",a);if(l.fadeOut){t.fadeOut((1-1/c)*l.duration)}var r=g(k[o]);var s={width:r.width()||l.width,height:r.height()||l.height};var u=r.clone().css(s).appendTo(d);u.from={left:0};u.to={left:(!n?1:-1)*u.width()*0.5};if(l.support.transform){u.from={translate:[u.from.left,0,0]};u.to={translate:[u.to.left,0,0]}}wowAnimate(u,u.from,u.to,l.duration,l.duration*0.1,"swing");for(var p=0;p<e.length;p++){var m=e[p];var v=g(k[q]).clone().css({position:"absolute",top:0}).css(s).appendTo(m);v.from={left:!n?(-v.width()):(v.width()-m.position().left)};v.to={left:-m.position().left};if(l.support.transform){v.from={translate:[v.from.left,0,0]};v.to={translate:[v.to.left,0,0]}}wowAnimate(v,v.from,v.to,(l.duration/(e.length+1))*(n?(e.length-p+1):(p+2)),"swing",((!n&&p==e.length-1||n&&!p)?function(){j.trigger("effectEnd");h.hide().find("img").remove();u.remove()}:false))}}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 7.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"",prev:"",next:"",duration:20*100,delay:88*100,width:600,height:800,autoPlay:true,autoPlayVideo:false,playPause:true,stopOnHover:true,loop:false,bullets:1,caption:false,captionEffect:"parallax",controls:true,responsive:1,fullScreen:false,gestures:2,onBeforeStep:0,images:0});